### PR TITLE
MetaData storage specification

### PR DESCRIPTION
**Pull request by andrershov**
This PR adds metadata storage specification to prove that the way our storage layer underlying Zen2 implementation works correctly.
This specification does no model multipath, only a single data path is modeled.

### CODE REVIEW

**Comment by andrershov** [comment]
@DaveCTurner thanks for your review! Modelling with domains looks much nicer. However, I'm not sure if we can avoid steps constraint. I've tried `newMeta < 4 /\ newManifest < 4` and seems that the model is hanging.
In fact, the model can take the infinite number of execution steps without incrementing newMeta using the following execution path `writeMeta -> writeMetaFail -> deleteMeta -> writeMeta -> writeMetaFail -> deleteMeta...`

**Comment by DaveCTurner** [comment]
> In fact, the model can take the infinite number of execution steps without incrementing `newMeta` using the following execution path...

This is true, but if you remove `steps` then the state space becomes finite. An infinite path through a finite state space can be checked in finite time, because the model checker deduplicates its states.

**Comment by andrershov** [comment]
@DaveCTurner thanks for your explanation, the reason why the model was running indefinitely is that I forgot to remove steps variable from the model and the number of states was infinite. Fixed by this commit https://github.com/elastic/elasticsearch-formal-models/pull/42/commits/d1346d78186153a8cfcbac9f332fca8a7e2564f8 .
I'm not sure if we shall commit the buggy version or correct implemented version to the repository. I think it's better to commit the correct implemented version.

**Comment by andrershov** [comment]
@DaveCTurner I've made a change to the specification by splitting deleteNew and deleteOld into separately deleting manifest and metadata files, which makes clearer in my opinion. Ready for the next pass.

**Pull request merged**
